# Generated by Django 4.2.4 on 2023-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('u_type', models.CharField(default='user', max_length=100)),
                ('u_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('photo', models.ImageField(upload_to='user_images')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
